using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using BasicToMips.UI.Simulator;

namespace BasicToMips.Simulator
{
    /// <summary>
    /// Registry for mapping device aliases to virtual devices
    /// Supports both traditional ALIAS (d0-d5) and DEVICE (named references) statements
    /// </summary>
    public class DeviceAliasRegistry
    {
        /// <summary>
        /// Map of alias name to virtual device
        /// </summary>
        private readonly Dictionary<string, VirtualDevice> _aliasMap = new(StringComparer.OrdinalIgnoreCase);

        /// <summary>
        /// Device pool for batch operations (lb/sb)
        /// </summary>
        private readonly DevicePool _devicePool;

        /// <summary>
        /// Regex pattern for parsing DEVICE statements: DEVICE aliasName "PrefabName"
        /// </summary>
        private static readonly Regex DevicePattern = new Regex(
            @"^\s*DEVICE\s+(\w+)\s+""([^""]+)""\s*$",
            RegexOptions.IgnoreCase | RegexOptions.Compiled
        );

        /// <summary>
        /// Regex pattern for parsing IC10 DEVICE comments: # DEVICE aliasName "PrefabName"
        /// Generated by compiler as: move rX hash  # DEVICE aliasName "PrefabName"
        /// </summary>
        private static readonly Regex IC10DevicePattern = new Regex(
            @"#\s*DEVICE\s+(\w+)\s+""([^""]+)""",
            RegexOptions.IgnoreCase | RegexOptions.Compiled
        );

        /// <summary>
        /// Constructor - creates registry with a new device pool
        /// </summary>
        public DeviceAliasRegistry()
        {
            _devicePool = new DevicePool();
        }

        /// <summary>
        /// Constructor - creates registry with an existing device pool
        /// </summary>
        /// <param name="devicePool">Existing device pool to use</param>
        public DeviceAliasRegistry(DevicePool devicePool)
        {
            _devicePool = devicePool ?? throw new ArgumentNullException(nameof(devicePool));
        }

        /// <summary>
        /// Gets the device pool for batch operations
        /// </summary>
        public DevicePool DevicePool => _devicePool;

        /// <summary>
        /// Register a device alias with its prefab name
        /// </summary>
        /// <param name="alias">The alias name (e.g., "sensor", "furnace")</param>
        /// <param name="prefabName">The prefab name (e.g., "StructureGasSensor")</param>
        public void RegisterAlias(string alias, string prefabName)
        {
            if (string.IsNullOrWhiteSpace(alias))
                throw new ArgumentException("Alias cannot be empty", nameof(alias));

            if (string.IsNullOrWhiteSpace(prefabName))
                throw new ArgumentException("Prefab name cannot be empty", nameof(prefabName));

            var device = new VirtualDevice(alias, prefabName);
            _aliasMap[alias] = device;

            // Add device to pool for batch operations
            _devicePool.AddDevice(device);
        }

        /// <summary>
        /// Get a virtual device by its alias name
        /// </summary>
        /// <param name="alias">The alias name</param>
        /// <returns>The virtual device, or null if not found</returns>
        public VirtualDevice? GetDevice(string alias)
        {
            return _aliasMap.TryGetValue(alias, out var device) ? device : null;
        }

        /// <summary>
        /// Check if an alias exists in the registry
        /// </summary>
        /// <param name="alias">The alias name to check</param>
        /// <returns>True if the alias exists</returns>
        public bool HasAlias(string alias)
        {
            return _aliasMap.ContainsKey(alias);
        }

        /// <summary>
        /// Clear all registered aliases and device pool
        /// </summary>
        public void Clear()
        {
            _aliasMap.Clear();
            _devicePool.Clear();
        }

        /// <summary>
        /// Get all registered aliases
        /// </summary>
        public IReadOnlyDictionary<string, VirtualDevice> GetAllDevices()
        {
            return _aliasMap;
        }

        /// <summary>
        /// Parse BASIC or IC10 code and register all DEVICE statements.
        /// Handles both BASIC format (DEVICE alias "Prefab") and IC10 comment format (# DEVICE alias "Prefab")
        /// </summary>
        /// <param name="code">The BASIC or IC10 code to parse</param>
        /// <returns>Number of devices registered</returns>
        public int ParseAndRegisterDevices(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
                return 0;

            int count = 0;
            var lines = code.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);

            foreach (var line in lines)
            {
                var trimmedLine = line.Trim();

                if (string.IsNullOrEmpty(trimmedLine))
                    continue;

                // Check for BASIC DEVICE statement (skip comment-only lines for this check)
                if (!trimmedLine.StartsWith("'") && !trimmedLine.StartsWith("#"))
                {
                    var match = DevicePattern.Match(trimmedLine);
                    if (match.Success)
                    {
                        var alias = match.Groups[1].Value;
                        var prefabName = match.Groups[2].Value;

                        if (!HasAlias(alias))
                        {
                            RegisterAlias(alias, prefabName);
                            count++;
                        }
                        continue;
                    }
                }

                // Check for IC10 DEVICE comment (anywhere in the line)
                // Format: move rX hash  # DEVICE aliasName "PrefabName"
                var ic10Match = IC10DevicePattern.Match(trimmedLine);
                if (ic10Match.Success)
                {
                    var alias = ic10Match.Groups[1].Value;
                    var prefabName = ic10Match.Groups[2].Value;

                    if (!HasAlias(alias))
                    {
                        RegisterAlias(alias, prefabName);
                        count++;
                    }
                }
            }

            return count;
        }

        /// <summary>
        /// Get count of registered devices
        /// </summary>
        public int Count => _aliasMap.Count;
    }
}
